"""Initial schema

Revision ID: ab65dde8dce0
Revises: ca800332cb8e
Create Date: 2026-04-21 08:09:35.690985

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "ab65dde8dce0"
down_revision: Union[str, Sequence[str], None] = "ca800332cb8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
