"""Initial schema: sessions, tasks, batches, jobs, results

Revision ID: c1aa6c8c9a3f
Revises: 
Create Date: 2026-04-20 17:14:26.932550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1aa6c8c9a3f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('session_ids', sa.JSON(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.Column('completed_sessions', sa.Integer(), nullable=True),
    sa.Column('failed_sessions', sa.Integer(), nullable=True),
    sa.Column('max_concurrent', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_operations_batch_id'), 'batch_operations', ['batch_id'], unique=True)
    op.create_index(op.f('ix_batch_operations_created_at'), 'batch_operations', ['created_at'], unique=False)
    op.create_index(op.f('ix_batch_operations_id'), 'batch_operations', ['id'], unique=False)
    op.create_table('download_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('state', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('completed_files', sa.Integer(), nullable=True),
    sa.Column('failed_files', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_sessions_created_at'), 'download_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_download_sessions_id'), 'download_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_download_sessions_session_id'), 'download_sessions', ['session_id'], unique=True)
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('cron_expression', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('next_run_time', sa.DateTime(), nullable=True),
    sa.Column('last_run_time', sa.DateTime(), nullable=True),
    sa.Column('session_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_jobs_created_at'), 'scheduled_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_scheduled_jobs_id'), 'scheduled_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_scheduled_jobs_job_id'), 'scheduled_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_scheduled_jobs_name'), 'scheduled_jobs', ['name'], unique=False)
    op.create_index(op.f('ix_scheduled_jobs_next_run_time'), 'scheduled_jobs', ['next_run_time'], unique=False)
    op.create_table('download_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('downloaded_size', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['download_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_tasks_created_at'), 'download_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_download_tasks_id'), 'download_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_download_tasks_task_id'), 'download_tasks', ['task_id'], unique=True)
    op.create_index(op.f('ix_download_tasks_url'), 'download_tasks', ['url'], unique=False)
    op.create_table('download_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('checksum_md5', sa.String(), nullable=True),
    sa.Column('checksum_sha256', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('download_time', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['download_tasks.task_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_results_created_at'), 'download_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_download_results_id'), 'download_results', ['id'], unique=False)
    op.create_index(op.f('ix_download_results_result_id'), 'download_results', ['result_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_download_results_result_id'), table_name='download_results')
    op.drop_index(op.f('ix_download_results_id'), table_name='download_results')
    op.drop_index(op.f('ix_download_results_created_at'), table_name='download_results')
    op.drop_table('download_results')
    op.drop_index(op.f('ix_download_tasks_url'), table_name='download_tasks')
    op.drop_index(op.f('ix_download_tasks_task_id'), table_name='download_tasks')
    op.drop_index(op.f('ix_download_tasks_id'), table_name='download_tasks')
    op.drop_index(op.f('ix_download_tasks_created_at'), table_name='download_tasks')
    op.drop_table('download_tasks')
    op.drop_index(op.f('ix_scheduled_jobs_next_run_time'), table_name='scheduled_jobs')
    op.drop_index(op.f('ix_scheduled_jobs_name'), table_name='scheduled_jobs')
    op.drop_index(op.f('ix_scheduled_jobs_job_id'), table_name='scheduled_jobs')
    op.drop_index(op.f('ix_scheduled_jobs_id'), table_name='scheduled_jobs')
    op.drop_index(op.f('ix_scheduled_jobs_created_at'), table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    op.drop_index(op.f('ix_download_sessions_session_id'), table_name='download_sessions')
    op.drop_index(op.f('ix_download_sessions_id'), table_name='download_sessions')
    op.drop_index(op.f('ix_download_sessions_created_at'), table_name='download_sessions')
    op.drop_table('download_sessions')
    op.drop_index(op.f('ix_batch_operations_id'), table_name='batch_operations')
    op.drop_index(op.f('ix_batch_operations_created_at'), table_name='batch_operations')
    op.drop_index(op.f('ix_batch_operations_batch_id'), table_name='batch_operations')
    op.drop_table('batch_operations')
    # ### end Alembic commands ###
