"""Initial schema: download_sessions, tasks, batches, jobs, results

Revision ID: ca800332cb8e
Revises: c1aa6c8c9a3f
Create Date: 2026-04-20 17:20:50.866464

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "ca800332cb8e"
down_revision: Union[str, Sequence[str], None] = "c1aa6c8c9a3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
